
export const enum Speciality {
    UROLOGY = "Urology",
    ONCOLOGY = "Oncology",
    NEUROLOGY = "Neurology",
    RADIOLOGY = "Radiology",
    PSYCHIATRY = "Psychiatry",
    CARDIOLOGY = "Cardiology",
    PEDIATRICS = "Pediatrics",
    DERMATOLOGY = "Dermatology",
    ORTHOPEDICS = "Orthopedics",
    PULMONOLOGY = "Pulmonology",
    RHEUMATOLOGY = "Rheumatology",
    ENDOCRINOLOGY = "Endocrinology",
    OPHTHALMOLOGY = "Ophthalmology",
    ANESTHESIOLOGY = "Anesthesiology",
    SURGERY_GENERAL = "General Surgery",
    FAMILY_MEDICINE = "Family Medicine",
    GASTROENTEROLOGY = "Gastroenterology",
    INTERNAL_MEDICINE = "Internal Medicine",
    EMERGENCY_MEDICINE = "Emergency Medicine",
    OBSTETRICS_GYNECOLOGY = "Obstetrics & Gynecology",
}
